# HTTP endpoint for fetching metrics
canister_query:http_request
# Transform functions for HTTP outcalls to exchanges, forex sources and listings
canister_query:transform_exchange_http_response
canister_query:transform_forex_http_response
canister_query:transform_listing_http_response
# Canister lifecycle
canister_heartbeat
canister_init
canister_inspect_message
canister_post_upgrade
canister_pre_upgrade
# Exported by the `main()` function in `main.rs`; cannot be called
main
