#!/usr/bin/env bash
set -euo pipefail

IP_SUPPORT=${IP_SUPPORT:-}
APPLICATION_SUBNET=${APPLICATION_SUBNET:-}
DISABLE_FOREX_WEEKEND_CHECK=${DISABLE_FOREX_WEEKEND_CHECK:-}
DISABLE_FOREX_TIMEZONE_OFFSET=${DISABLE_FOREX_TIMEZONE_OFFSET:-}

if [ -z "${IP_SUPPORT}" ]; then
    IP_SUPPORT="ipv4"
fi

if [ -z "${APPLICATION_SUBNET}" ]; then
    APPLICATION_SUBNET="no"
fi

if [ -z "${DISABLE_FOREX_WEEKEND_CHECK}" ]; then
    DISABLE_FOREX_WEEKEND_CHECK="no"
fi

if [ -z "${DISABLE_FOREX_TIMEZONE_OFFSET}" ]; then
    DISABLE_FOREX_TIMEZONE_OFFSET="no"
fi

FEATURES=()

if [ "${IP_SUPPORT}" == "ipv4" ]; then
    FEATURES+=('--features' 'ipv4-support')
fi

if [ "${APPLICATION_SUBNET}" == "yes" ]; then
    FEATURES+=('--features' 'application-subnet')
fi

if [ "${DISABLE_FOREX_WEEKEND_CHECK}" == "yes" ]; then
    FEATURES+=('--features' 'disable-forex-weekend-check')
fi

if [ "${DISABLE_FOREX_TIMEZONE_OFFSET}" == "yes" ]; then
    FEATURES+=('--features' 'disable-forex-timezone-offset')
fi

echo "IP_SUPPORT: $IP_SUPPORT"
echo "APPLICATION_SUBNET: $APPLICATION_SUBNET"
echo "DISABLE_FOREX_WEEKEND_CHECK: $DISABLE_FOREX_WEEKEND_CHECK"
echo "DISABLE_FOREX_TIMEZONE: $DISABLE_FOREX_TIMEZONE_OFFSET"

if [ ${#FEATURES[@]} -eq 0 ]; then
    cargo build -p xrc --target wasm32-unknown-unknown --release
else
    cargo build -p xrc --target wasm32-unknown-unknown --release "${FEATURES[@]}"
fi

