#!/usr/bin/env bash
set -euo pipefail

cargo install ic-wasm --version 0.3.0 --root ./target

IP_SUPPORT=${IP_SUPPORT:-}

if [ -z "${IP_SUPPORT}" ]; then
    IP_SUPPORT="ipv4"
fi

echo "checking IPv4 support feature flag"
if [ "${IP_SUPPORT}" == "ipv4" ]; then
    cargo build -p xrc --target wasm32-unknown-unknown --release --features ipv4-support
else
    cargo build -p xrc --target wasm32-unknown-unknown --release
fi

./target/bin/ic-wasm ./target/wasm32-unknown-unknown/release/xrc.wasm \
    -o ./target/wasm32-unknown-unknown/release/xrc.wasm shrink

./target/bin/ic-wasm \
    ./target/wasm32-unknown-unknown/release/xrc.wasm \
    -o ./target/wasm32-unknown-unknown/release/xrc.wasm \
    metadata candid:service --visibility public --file src/xrc/xrc.did