#!/usr/bin/env bash
# vim: ft=bash
# Build xrc.wasm inside docker. This outputs a single file, xrc.wasm,
# in the top-level directory.

set -euo pipefail

# Make sure we always run from the root
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPTS_DIR/.."

function title() {
    echo "Build Exchange Rate Canister (xrc) inside Docker"
}

function usage() {
    cat << EOF

Usage:
  $0

EOF
}

function help() {
    cat << EOF

This will create (and override) "./xrc.wasm".
EOF
}

## Building

function build() {
    image_name="xrc"
    docker_build_args=( --target scratch )
    docker_build_args+=( --build-arg IP_SUPPORT="$IP_SUPPORT" )
    docker_build_args+=(--tag "$image_name" .)

    echo "The following image name will be used: $image_name"

    tmp_outdir=$(mktemp -d)

    set -x
    DOCKER_BUILDKIT=1 docker build "${docker_build_args[@]}" --output "$tmp_outdir" --progress plain
    set +x

    echo "Copying build output from $tmp_outdir to $PWD"
    cp "$tmp_outdir/xrc.wasm" .

    echo "Removing $tmp_outdir"
    rm -rf "$tmp_outdir"
}

# ARGUMENT PARSING

while [[ $# -gt 0 ]]
do
    case $1 in
        --help)
            title
            usage
            help
            exit 0
            ;;
        *)
            echo "ERROR: unknown argument $1"
            usage
            echo
            echo "Use 'release --help' for more information."
            exit 1
            ;;
    esac
done

build
