#!/usr/bin/env bash
# vim: ft=bash
# Build xrc.wasm and then run it through the e2e-tests 

./scripts/docker-build
mkdir -p src/xrc-tests/gen/canister
mv xrc.wasm src/xrc-tests/gen/canister
docker-compose -f src/xrc-tests/docker/docker-compose.yml build base
cargo test --package xrc-tests --lib -- --exact --nocapture
