#!/usr/bin/env bash

cargo install wasm-opt --version 0.110.2 --root ./target
cargo install ic-wasm --version 0.3.0 --root ./target
cargo build -p xrc --target wasm32-unknown-unknown --release --features ipv4-support
./target/bin/ic-wasm ./target/wasm32-unknown-unknown/release/xrc.wasm \
    -o ./target/wasm32-unknown-unknown/release/xrc.wasm shrink
./target/bin/wasm-opt -Os -o ./target/wasm32-unknown-unknown/release/xrc.wasm ./target/wasm32-unknown-unknown/release/xrc.wasm