# Steps:
# 1. Build the xrc
# 2. Push the release out.

name: "release"

on:
  push:
    branches:
      - main
  pull_request:

env:
  DFX_VERSION: "0.14.1"

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Build canister
        uses: ./.github/actions/build
        with:
          assets_dir: 'out'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build canister
        run: |
          dfx build --network ic

      - name: Release
        uses: "softprops/action-gh-release@v1"
        with:
          files: .dfx/ic/canisters/service/service.wasm